OnlineBookStore/Areas/Admin/Controllers/BookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineBookStore.Data.Repository.IRepository;
using OnlineBookStore.Data.ViewModel;
using OnlineBookStore.Models.Models;
using OnlineBookStore.Utils;

namespace OnlineBookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class BookController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BookController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var books = _unitOfWork.BookRepository
                .GetAll()
                .ToList();

            if (books is null) return NotFound();

            return View(books);
        }

        public IActionResult Create()
        {
            List<Category> categoryList = _unitOfWork.CategoryRepository.GetAll().ToList();

            if (categoryList is null) return NotFound();

            BookCreateViewModel bookCreateViewModel = new BookCreateViewModel
            {
                book = new Book(),
                categories = categoryList
            };

            return View(bookCreateViewModel);
        }

        [HttpPost]
        public IActionResult Create(Book book)
        {
            if(book is not null)
            {
                book.Price = decimal.Parse(book.Price.ToString("0.00"));
                _unitOfWork.BookRepository.Add(book);
                _unitOfWork.Save();
                TempData["success"] = "The book has been added successfully.";
            }

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if(id == 0 || id is null)
            {
                return NotFound();
            }

            Book? book = _unitOfWork.BookRepository.Get(q => q.Id == id);

            if(book is null)
            {
                return NotFound();
            }

            return View(book);
        }

        [HttpPost]
        public IActionResult Edit(Book book)
        {
            if (book is not null)
            {
                _unitOfWork.BookRepository.Update(book);
                _unitOfWork.Save();
                TempData["success"] = "The book has been updated successfully.";

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == 0 || id is null)
            {
                return NotFound();
            }

            Book book = _unitOfWork.BookRepository.Get(q => q.Id == id);

            if (book is null) return NotFound();

            _unitOfWork.BookRepository.Remove(book);
            _unitOfWork.Save();
            TempData["success"] = "The book has been deleted successfully.";

            return RedirectToAction("Index");
        }
    }
}

OnlineBookStore/Areas/Customer/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineBookStore.Data.Repository.IRepository;
using OnlineBookStore.Models.Models;

namespace OnlineBookStore.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class BookController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BookController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Book> books = _unitOfWork.BookRepository.GetAll().ToList();
            return View(books);
        }

        public IActionResult Create()
        {
            return View();
        }
    }
}

OnlineBookStore/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineBookStore.Data;
using OnlineBookStore.Models;

namespace OnlineBookStore.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {   
            List<Category> categories = _db.Categories.ToList();
            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category obj)
        {
            if (ModelState.IsValid)
            {
                _db.Categories.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "The category has been created successfully.";
            }

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Category? obj = _db.Categories.FirstOrDefault(q => q.Id == id);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                _db.Categories.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "The category has been updated successfully.";
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Delete(int? id)
        {
            if(id == null || id == 0) return NotFound();

            Category? obj = _db.Categories.FirstOrDefault(q => q.Id == id);

            if (obj == null) return NotFound();

            _db.Categories.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "The category has been deleted successfully.";

            return RedirectToAction("Index");
        }
    }
}

OnlineBookStore/Areas/Customer/Views/Book/Create.cshtml
@model Book

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Add New Book</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <div class="border p-3">
                <div asp-validation-summary="ModelOnly"></div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Title" class="form-control border-0 shadow" />
                    <label asp-for="Title" class="ms-2"></label>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Author" class="form-control border-0 shadow" />
                    <label asp-for="Author" class="ms-2"></label>
                    <span asp-validation-for="Author" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <textarea asp-for="Description" class="form-control border-0 shadow"></textarea>
                    <label asp-for="Description" class="ms-2"></label>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Genre" class="form-control border-0 shadow" />
                    <label asp-for="Genre" class="ms-2"></label>
                    <span asp-validation-for="Genre" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="PublishedDate" type="date" class="form-control border-0 shadow" />
                    <label asp-for="PublishedDate" class="ms-2"></label>
                    <span asp-validation-for="PublishedDate" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Price" type="number" class="form-control border-0 shadow" />
                    <label asp-for="Price" class="ms-2"></label>
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>

                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control rounded-0">Add</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Book" asp-area="Customer" asp-action="Index" class="btn btn-outline-primary border form-control rounded-0">
                            Back to List
                        </a>
                    </div>
                </div>


            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

OnlineBookStore/Areas/Customer/Views/Book/Index.cshtml
@model List<Book>
@{
    ViewData["Title"] = "Books Page";
}

<div class="container">
    <div class="row pt-4 pb-2">
        <div class="col-6">
            <h2 class="text-primary">Book List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-action="Create" class="btn btn-primary rounded-0">
                <i class="bi bi-plus-circle"></i> Add New Book
            </a>
        </div>
    </div>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Published Date</th>
                <th>Genre</th>
                <th>Price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model)
            {
                <tr>
                    <td>@book.Title</td>
                    <td>@book.Author</td>
                    <td>@book.PublishedDate</td>
                    <td>@book.Genre</td>
                    <td>@book.Price</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Category" asp-action="Edit" asp-route-id="@book.Id" class="btn btn-primary rounded-0">
                                <i class="bi bi-pencil-square"></i> Edit
                            </a>
                            <a asp-controller="Category" asp-action="Delete" asp-route-id="@book.Id" class="btn btn-danger rounded-0">
                                <i class="bi bi-trash-fill"></i> Delete
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>